/* 由 build_lords.js 自动生成，勿手改。源：名册 emperor_note ＋ 用户两份表（user_lords_supplement.csv／user_lords_multi.csv）＋ emperor_bio.js 的生卒年。
 * 一座陵 1..N 个陵主；本产物只搬运，不改写、不补全、不用模型记忆添事实（PRD §9.1）。 */
;(function (root, mod) {
  if (typeof module === "object" && module.exports) module.exports = mod;
  else root.__LORDS__ = mod;
}(typeof self !== "undefined" ? self : this, {
 "meta": {
  "purpose": "「陵墓实体＋陵主实体」一对多里的陵主侧。名册的 emperor_note 是一句中文，九个帝、九个葬年、两种归属置信度全挤在一串里；拆成逐主行后，「推定」这类判断落到 attribution 字段上，可按它筛选，不再只是中文尾巴。",
  "rule": "status 只描述\"这个人的年代知不知道\"，attribution 只描述\"这个人属不属于这座陵\"，两者互不顶替；陵号与陵址之争（万安陵那类）仍由陵级 certainty 表达，不占 status。生卒年只有一个家：搬进本产物后 bio 的 life_* 那一套退役。无源一律 null，界面按 §9.2 渲染「⚠️ 暂未获取」，不许 0 占位。call 存庙号／谥号／追尊／陵号（西夏那一组源给的就是陵号），lord 存名册或用户写的原名，括号里的说明逐字留在 lord 里，不替它拆。",
  "vocab": {
   "status": [
    "ok",
    "unknown_birth",
    "unknown_burial",
    "unknown_years",
    "legendary_or_disputed"
   ],
   "attribution": [
    "confirmed",
    "presumed"
   ],
   "src": [
    "roster",
    "supplement",
    "emperors",
    "handoff"
   ],
   "ysrc": [
    "supplement",
    "emperors",
    "cbdb",
    "handoff"
   ]
  },
  "source_labels": {
   "roster": "名册称谓列",
   "supplement": "用户补录表",
   "emperors": "用户提供《emperors_birth_death.csv》",
   "handoff": "用户补录（2026-09-15 交付文档多主表）",
   "cbdb": "CBDB（经帝陵↔CBDB 生平连接）",
   "bio": "生卒年连接表（同卡上「生卒年」那一格）"
  },
  "files": {
   "per_lord": "user_lords_multi.csv",
   "supplement": "user_lords_supplement.csv",
   "roster": "emperor-star-map/utils/tomb_data.js",
   "years": "emperor-star-map/utils/emperor_bio.js"
  },
  "built": "2026-09-15",
  "tombs": 219,
  "lords": 250,
  "multi_tombs": 16,
  "single_tombs": 203,
  "injected_rows": 6,
  "presumed_rows": 18,
  "unnamed_rows": 1,
  "dated_rows": 180,
  "tombs_all_lords_undated": 57,
  "by_status": "ok=170 unknown_birth=7 unknown_burial=1 unknown_years=16 legendary_or_disputed=6",
  "by_name_src": "roster=207 supplement=16 emperors=4 handoff=23",
  "by_year_src": "supplement=31 emperors=128 cbdb=7 handoff=16",
  "max_lords": 9
 }
,
 "by_tomb_id": {
  "qin-shihuang-ling": [{"lord":"嬴政","call":"秦始皇","birth":-259,"death":-210,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":2,"note":null}],
  "han-changling": [{"lord":"刘邦","call":"汉高祖","birth":-256,"death":-195,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":4,"note":null}],
  "han-anling": [{"lord":"刘盈","call":"汉惠帝","birth":-205,"death":-188,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":5,"note":null}],
  "han-yangling": [{"lord":"刘启","call":"汉景帝","birth":-188,"death":-140,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":7,"note":null}],
  "han-maoling": [{"lord":"刘彻","call":"汉武帝","birth":-156,"death":-87,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":8,"note":null}],
  "han-pingling": [{"lord":"刘弗陵","call":"汉昭帝","birth":-94,"death":-73,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":9,"note":null}],
  "han-weiling": [{"lord":"刘奭","call":"汉元帝","birth":-75,"death":-33,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":11,"note":null}],
  "han-yanling": [{"lord":"刘骜","call":"汉成帝","birth":-52,"death":-7,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":12,"note":null}],
  "han-yiling": [{"lord":"刘欣","call":"汉哀帝","birth":-25,"death":-1,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":13,"note":null}],
  "han-kangling-xi": [{"lord":"刘衎","call":"汉平帝","birth":-9,"death":6,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":14,"note":null}],
  "han-baling": [{"lord":"刘恒","call":"汉文帝","birth":-202,"death":-157,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":6,"note":null}],
  "han-duling": [{"lord":"刘询","call":"汉宣帝","birth":-91,"death":-49,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":10,"note":null}],
  "han-yunling": [{"lord":"赵倢伃（追尊）","call":"汉昭帝生母","birth":null,"death":-88,"burial":-88,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":2,"note":"卒年为约数"}],
  "tang-xingning-ling": [{"lord":"李昞（追尊世祖）","call":"唐高祖之父","birth":null,"death":572,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":11,"note":"北周建德元年卒；葬年无可靠记载"}],
  "tang-yongkang-ling": [{"lord":"李虎（追尊太祖）","call":"唐高祖之祖","birth":null,"death":551,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":12,"note":"西魏大统十七年卒；葬年无可靠记载"}],
  "han-yuanling": [{"lord":"刘秀","call":"汉光武帝","birth":-4,"death":57,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":15,"note":null}],
  "han-shenling": [{"lord":"刘肇","call":"汉和帝","birth":80,"death":106,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":18,"note":null}],
  "han-jingling-dong": [{"lord":"刘炟","call":"汉章帝","birth":57,"death":89,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":17,"note":null}],
  "han-gongling": [{"lord":"劉祐","call":"汉安帝","birth":98,"death":125,"burial":null,"status":"ok","attribution":"confirmed","src":"emperors","line":20,"ysrc":"emperors","yline":20,"note":null}],
  "han-xianling": [{"lord":"劉保","call":"汉顺帝","birth":116,"death":145,"burial":null,"status":"ok","attribution":"confirmed","src":"emperors","line":21,"ysrc":"emperors","yline":21,"note":null}],
  "han-huailling": [{"lord":"劉炳","call":"汉冲帝","birth":144,"death":146,"burial":null,"status":"ok","attribution":"confirmed","src":"emperors","line":22,"ysrc":"emperors","yline":22,"note":null}],
  "han-wenling": [{"lord":"刘宏","call":"汉灵帝","birth":156,"death":189,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":25,"note":null}],
  "han-jingling2": [{"lord":"刘缵","call":"汉质帝","birth":139,"death":147,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":23,"note":null}],
  "han-xuanling": [{"lord":"刘志","call":"汉桓帝","birth":133,"death":168,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":24,"note":null}],
  "han-kangling-dong": [{"lord":"劉隆","call":"汉殇帝","birth":106,"death":107,"burial":null,"status":"ok","attribution":"confirmed","src":"emperors","line":19,"ysrc":"emperors","yline":19,"note":null}],
  "han-chanling": [{"lord":"刘协","call":"汉献帝","birth":190,"death":234,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":27,"note":null}],
  "beiwei-yonggu-ling": [{"lord":"冯氏","call":"北魏文明太皇太后","birth":442,"death":490,"burial":490,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":3,"note":"中国国家博物馆定为冯太后陵"}],
  "beiwei-changling": [{"lord":"元宏","call":"北魏孝文帝","birth":467,"death":499,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":78,"note":null}],
  "beiwei-dingling": [{"lord":"元诩","call":"北魏孝明帝","birth":504,"death":528,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":80,"note":null}],
  "beizhou-xiaoling": [{"lord":"宇文邕","call":"北周武帝","birth":542,"death":578,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":95,"note":null}],
  "beizhou-chengling": [{"lord":"宇文泰（追尊）","call":"北周文帝","birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "sui-tailing": [{"lord":"杨坚","call":"隋文帝","birth":541,"death":604,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":98,"note":null}],
  "sui-yangdi-mu": [{"lord":"杨广","call":"隋炀帝","birth":580,"death":618,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":99,"note":null}],
  "sui-yangdi-jiu": [{"lord":"杨广（旧传葬地）","call":"隋炀帝","birth":569,"death":618,"burial":null,"status":"unknown_burial","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":17,"note":"生年取 569（旧表 580 与维基/Wikidata 不合）；葬地多说"}],
  "cao-cao-gaoling": [{"lord":"曹操（追尊魏武帝）","call":null,"birth":155,"death":220,"burial":220,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":19,"note":"追尊帝与历史人物陵的分类差异已在状态里说明"}],
  "cao-pi-shouyang-ling": [{"lord":"曹丕","call":"魏文帝","birth":187,"death":226,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":28,"note":null}],
  "liu-bei-huiling": [{"lord":"刘备","call":"蜀汉昭烈帝","birth":161,"death":223,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":33,"note":null}],
  "sun-quan-jiangling": [{"lord":"孙权","call":"吴大帝","birth":182,"death":252,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":35,"note":null}],
  "tang-xianling": [{"lord":"李渊","call":"唐高祖","birth":566,"death":635,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":101,"note":null}],
  "tang-zhaoling": [{"lord":"李世民","call":"唐太宗","birth":598,"death":649,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":102,"note":null}],
  "tang-qianling": [{"lord":"李治","call":"唐高宗","birth":628,"death":683,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}, {"lord":"武则天","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "tang-dingling": [{"lord":"李显","call":"唐中宗","birth":656,"death":710,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":104,"note":null}],
  "tang-qiaoling": [{"lord":"李旦","call":"唐睿宗","birth":662,"death":716,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":105,"note":null}],
  "tang-tailing": [{"lord":"李隆基","call":"唐玄宗","birth":685,"death":762,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":106,"note":null}],
  "tang-jianling": [{"lord":"李亨","call":"唐肃宗","birth":711,"death":762,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":107,"note":null}],
  "tang-yuanling": [{"lord":"李豫","call":"唐代宗","birth":727,"death":779,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":108,"note":null}],
  "tang-chongling": [{"lord":"李适","call":"唐德宗","birth":742,"death":805,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":109,"note":null}],
  "tang-jingling-tang": [{"lord":"李纯","call":"唐宪宗","birth":772,"death":820,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":111,"note":null}],
  "tang-guangling": [{"lord":"李恒","call":"唐穆宗","birth":794,"death":824,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":112,"note":null}],
  "tang-zhangling": [{"lord":"李昂","call":"唐文宗","birth":808,"death":840,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":114,"note":null}],
  "tang-duanling": [{"lord":"李炎","call":"唐武宗","birth":814,"death":846,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":115,"note":null}],
  "tang-zhenling": [{"lord":"李忱","call":"唐宣宗","birth":810,"death":859,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":116,"note":null}],
  "tang-jianling2": [{"lord":"李漼","call":"唐懿宗","birth":833,"death":873,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":117,"note":null}],
  "tang-jingling": [{"lord":"李儇","call":"唐僖宗","birth":862,"death":888,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":118,"note":null}],
  "tang-zhuangling": [{"lord":"李湛","call":"唐敬宗","birth":808,"death":826,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":113,"note":null}],
  "tang-fengling": [{"lord":"李诵","call":"唐顺宗","birth":761,"death":806,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":110,"note":null}],
  "tang-heling": [{"lord":"李晔","call":"唐昭宗","birth":867,"death":904,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":119,"note":null}],
  "tang-gongling": [{"lord":"李弘（追尊孝敬皇帝）","call":"唐太子","birth":652,"death":675,"burial":675,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":13,"note":null}],
  "tang-shunling": [{"lord":"杨氏（追封太原王妃）","call":"武则天之母","birth":null,"death":670,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":15,"note":"670 卒，追尊与改称顺陵的年代另说"}],
  "tang-huiling": [{"lord":"李宪（追尊）","call":"唐让帝","birth":679,"death":742,"burial":742,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":14,"note":null}],
  "houtang-huiling": [{"lord":"李嗣源","call":"后唐明宗","birth":867,"death":933,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":125,"note":null}],
  "houzhou-songling": [{"lord":null,"call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "houzhou-qingling": [{"lord":"柴荣","call":"后周世宗","birth":921,"death":959,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":133,"note":null}],
  "houzhou-shunling": [{"lord":"柴宗训","call":"后周恭帝","birth":953,"death":973,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":134,"note":null}],
  "houjin-xianling": [{"lord":"石敬瑭","call":"后晋高祖","birth":892,"death":942,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":128,"note":null}],
  "qianshu-yongling": [{"lord":"前蜀高祖王建","call":null,"birth":847,"death":918,"burial":918,"status":"ok","attribution":"confirmed","src":"supplement","line":20,"ysrc":"supplement","yline":20,"note":"后梁开平二年卒、葬永陵"}],
  "houshu-heling": [{"lord":"后蜀高祖孟知祥","call":null,"birth":874,"death":934,"burial":934,"status":"ok","attribution":"confirmed","src":"supplement","line":21,"ysrc":"supplement","yline":21,"note":"934 建国同年卒、葬和陵"}],
  "nantang-erling": [{"lord":"李昪","call":"南唐烈主","birth":889,"death":943,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":32,"ysrc":"supplement","yline":32,"note":"两位皇帝各记各的年，不合并"}, {"lord":"李璟","call":"中主","birth":916,"death":961,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":32,"ysrc":"supplement","yline":32,"note":null}],
  "song-yongan-ling": [{"lord":"赵弘殷（追尊）","call":"宋宣祖","birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "song-yongchang-ling": [{"lord":"赵匡胤","call":"宋太祖","birth":927,"death":976,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":138,"note":null}],
  "song-yongxi-ling": [{"lord":"赵光义","call":"宋太宗","birth":939,"death":997,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":139,"note":null}],
  "song-yongding-ling": [{"lord":"赵恒","call":"宋真宗","birth":968,"death":1022,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":140,"note":null}],
  "song-yongzhao-ling": [{"lord":"赵祯","call":"宋仁宗","birth":1010,"death":1063,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":141,"note":null}],
  "song-yonghou-ling": [{"lord":"赵曙","call":"宋英宗","birth":1032,"death":1067,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":142,"note":null}],
  "song-yongyu-ling": [{"lord":"赵顼","call":"宋神宗","birth":1048,"death":1085,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":143,"note":null}],
  "song-yongtai-ling": [{"lord":"赵煦","call":"宋哲宗","birth":1076,"death":1100,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":144,"note":null}],
  "song-zuling": [{"lord":"赵氏先祖群","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"supplement","line":28,"ysrc":null,"yline":null,"note":"名册作「宋太祖之高祖、曾祖、祖父（追尊）」，是关系串不是人名；源未具名，早期几代生卒史料不足"}],
  "nansong-liuling": [{"lord":"南宋高宗至度宗六帝（攒宫）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "liao-zuling": [{"lord":"耶律阿保机","call":"辽太祖","birth":872,"death":926,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":155,"note":null}],
  "liao-qingling": [{"lord":"耶律隆绪","call":"辽圣宗","birth":972,"death":1031,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":33,"ysrc":"supplement","yline":33,"note":"故宫《辽史本纪》页给出兴宗、道宗年代"}, {"lord":"耶律宗真","call":"兴宗","birth":1016,"death":1055,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":33,"ysrc":"supplement","yline":33,"note":"故宫《辽史本纪》页给出兴宗、道宗年代"}, {"lord":"耶律洪基","call":"道宗","birth":1032,"death":1101,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":33,"ysrc":"supplement","yline":33,"note":"故宫《辽史本纪》页给出兴宗、道宗年代"}],
  "liao-huailling": [{"lord":"耶律德光","call":"辽太宗","birth":902,"death":947,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":156,"note":null}],
  "liao-xianling": [{"lord":"耶律阮","call":"辽世宗","birth":918,"death":951,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":157,"note":null}],
  "liao-qianling": [{"lord":"耶律贤","call":"辽景宗","birth":948,"death":982,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":159,"note":null}],
  "jin-huangling": [{"lord":null,"call":"太祖","birth":1068,"death":1123,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表第 34 行只作「太祖至哀宗，且并非所有金帝皆葬此」，未逐位说明谁葬此，故七主一律标 presumed；庙号与年代取交付文档多主表，未给名讳故不补名"}, {"lord":null,"call":"太宗","birth":1075,"death":1135,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}, {"lord":null,"call":"熙宗","birth":1119,"death":1150,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}, {"lord":null,"call":"世宗","birth":1123,"death":1189,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}, {"lord":null,"call":"章宗","birth":1168,"death":1208,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}, {"lord":null,"call":"宣宗","birth":1163,"death":1224,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}, {"lord":null,"call":"哀宗","birth":1198,"death":1234,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"补录表未逐位说明谁葬此，故标 presumed；未给名讳故不补名"}],
  "xixia-ling": [{"lord":"继迁","call":"裕陵","birth":963,"death":1004,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定；源未说 6、7 号陵是哪两位，故九主一律标 presumed"}, {"lord":"德明","call":"嘉陵","birth":981,"death":1032,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"元昊","call":"泰陵","birth":1003,"death":1048,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"谅祚","call":"安陵","birth":1047,"death":1068,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"秉常","call":"献陵","birth":1061,"death":1086,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"乾顺","call":"显陵","birth":1083,"death":1139,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"仁孝","call":"寿陵","birth":1124,"death":1193,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"纯祐","call":"庄陵","birth":1177,"death":1206,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}, {"lord":"安全","call":"康陵","birth":1181,"death":1211,"burial":null,"status":"ok","attribution":"presumed","src":"handoff","line":null,"ysrc":"handoff","yline":null,"note":"宁夏文物考古所：除 6、7 号陵外多为推定"}],
  "yuan-qiniangu": [{"lord":"成吉思汗以下元代诸帝","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "chengjisihan-ling": [{"lord":"铁木真","call":"成吉思汗","birth":1162,"death":1227,"burial":null,"status":"legendary_or_disputed","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":18,"note":"生年为传统纪年；今陵属纪念性体系，不可把卒年当葬年"}],
  "ming-zuling": [{"lord":"朱氏先祖群","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"supplement","line":29,"ysrc":null,"yline":null,"note":"名册作「明太祖之高祖、曾祖、祖父（追尊）」，是关系串不是人名；源未具名，故按群记一行"}],
  "ming-huangling": [{"lord":"朱世珍","call":"仁祖淳皇帝","birth":1281,"death":1344,"burial":null,"status":"ok","attribution":"confirmed","src":"supplement","line":30,"ysrc":"supplement","yline":30,"note":"名册作「明太祖之父 朱世珍」"}, {"lord":"陈氏","call":null,"birth":null,"death":1344,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"supplement","line":30,"ysrc":"supplement","yline":30,"note":"年取该行出处列「陈氏生年不可考、同卒 1344」"}],
  "ming-xianling": [{"lord":"朱祐杬（追尊睿宗）","call":"明世宗生父","birth":1476,"death":1519,"burial":1520,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":16,"note":"1520 葬松林山，嘉靖朝升格为帝陵；与蒋氏合葬"}, {"lord":"蒋氏","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"补录表第 16 行出处列「与蒋氏合葬」，交付文档单陵主表作「朱祐杬＋蒋氏」，生卒两格写作 unknown_birth 与「?」——两值皆无源"}],
  "ming-xiaoling": [{"lord":"朱元璋","call":"明太祖","birth":1328,"death":1398,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":194,"note":null}, {"lord":"马氏","call":"孝慈高皇后","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "ming-changling": [{"lord":"朱棣","call":"明成祖","birth":1360,"death":1424,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":196,"note":null}, {"lord":"徐氏","call":"仁孝文皇后","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "ming-xianling2": [{"lord":"朱高炽","call":"明仁宗","birth":1378,"death":1425,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":197,"note":null}],
  "ming-jingling": [{"lord":"朱瞻基","call":"明宣宗","birth":1398,"death":1435,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":198,"note":null}],
  "ming-yuling-ming": [{"lord":"朱祁镇","call":"明英宗","birth":1427,"death":1464,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":199,"note":null}],
  "ming-maoling-ming": [{"lord":"朱见深","call":"明宪宗","birth":1447,"death":1487,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":201,"note":null}],
  "ming-tailing-ming": [{"lord":"朱祐樘","call":"明孝宗","birth":1470,"death":1505,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":202,"note":null}],
  "ming-kangling-ming": [{"lord":"朱厚照","call":"明武宗","birth":1491,"death":1521,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":203,"note":null}],
  "ming-yongling-ming": [{"lord":"朱厚熜","call":"明世宗","birth":1508,"death":1566,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":204,"note":null}],
  "ming-zhaoling-ming": [{"lord":"朱载坖","call":"明穆宗","birth":1537,"death":1572,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":205,"note":null}],
  "ming-dingling-ming": [{"lord":"朱翊钧","call":"明神宗","birth":1563,"death":1620,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":206,"note":null}],
  "ming-qingling-ming": [{"lord":"朱常洛","call":"明光宗","birth":1582,"death":1620,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":207,"note":null}],
  "ming-siling": [{"lord":"朱由检（崇祯帝）","call":"明毅宗","birth":1611,"death":1644,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":209,"note":null}],
  "qing-yongling": [{"lord":"孟特穆","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"补录表第 31 行作「努尔哈赤先祖群（孟特穆、福满、觉昌安、塔克世等）」，六名取交付文档多主表；早期生年不宜按公历硬填"}, {"lord":"福满","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"源只给名，未给年"}, {"lord":"觉昌安","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"源只给名，未给年"}, {"lord":"塔克世","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"源只给名，未给年"}, {"lord":"礼敦","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"礼敦仅见于交付文档多主表，补录表用「等」带过"}, {"lord":"塔察篇古","call":null,"birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"handoff","line":null,"ysrc":null,"yline":null,"note":"交付文档在名后写「及配偶」，配偶未具名，本表不替她们造行"}],
  "qing-fuling": [{"lord":"努尔哈赤","call":"清太祖","birth":1559,"death":1626,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":210,"note":null}, {"lord":"叶赫那拉氏","call":"孝慈高皇后","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "qing-zhaoling-qing": [{"lord":"皇太极","call":"清太宗","birth":1592,"death":1643,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":211,"note":null}, {"lord":"博尔济吉特氏","call":"孝端文皇后","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "qing-xiaoling": [{"lord":"福临（顺治帝）","call":"清世祖","birth":1638,"death":1661,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":212,"note":null}],
  "qing-jingling": [{"lord":"玄烨（康熙帝）","call":"清圣祖","birth":1654,"death":1722,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":213,"note":null}],
  "qing-yuling-qing": [{"lord":"弘历（乾隆帝）","call":"清高宗","birth":1711,"death":1799,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":215,"note":null}],
  "qing-dingling-qing": [{"lord":"奕詝（咸丰帝）","call":"清文宗","birth":1831,"death":1861,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":218,"note":null}],
  "qing-huiling-qing": [{"lord":"载淳（同治帝）","call":"清穆宗","birth":1856,"death":1874,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":219,"note":null}],
  "qing-zhaoxiling": [{"lord":"博尔济吉特氏","call":"孝庄文皇后","birth":1613,"death":1688,"burial":1725,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":4,"note":"1688 仅暂安，1725 葬入地宫"}],
  "qing-puxiangyu": [{"lord":"钮祜禄氏（慈安太后）","call":"孝贞显皇后","birth":1837,"death":1881,"burial":1881,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":5,"note":"故宫载是年九月入葬"}],
  "qing-putuoyu": [{"lord":"叶赫那拉氏（慈禧太后）","call":"孝钦显皇后","birth":1835,"death":1908,"burial":1909,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":6,"note":"卒 1908-11-15，葬 1909"}],
  "qing-xiaodongling": [{"lord":"博尔济吉特氏","call":"孝惠章皇后","birth":1641,"death":1718,"burial":1718,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":7,"note":null}],
  "qing-baohuayu": [{"lord":"旻宁（道光帝）初营陵址","call":"清宣宗","birth":1782,"death":1850,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":217,"note":null}],
  "qing-tailing-qing": [{"lord":"胤禛（雍正帝）","call":"清世宗","birth":1678,"death":1735,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":214,"note":null}],
  "qing-taidongling": [{"lord":"钮祜禄氏（乾隆生母）","call":"孝圣宪皇后","birth":1692,"death":1777,"burial":1777,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":8,"note":null}],
  "qing-changling-qing": [{"lord":"颙琰（嘉庆帝）","call":"清仁宗","birth":1760,"death":1820,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":216,"note":null}],
  "qing-changxiling": [{"lord":"钮祜禄氏","call":"孝和睿皇后","birth":1776,"death":1849,"burial":1853,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":9,"note":"卒年 1849 与 1850 两说并存，待回源"}],
  "qing-muling-qing": [{"lord":"旻宁（道光帝）","call":"清宣宗","birth":1782,"death":1850,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":217,"note":null}],
  "qing-mudongling": [{"lord":"博尔济吉特氏","call":"孝静成皇后","birth":1812,"death":1855,"burial":1857,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":10,"note":"卒与葬不同年"}],
  "qing-chongling": [{"lord":"载湉（光绪帝）","call":"清德宗","birth":1871,"death":1908,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":220,"note":null}],
  "huangdi-ling": [{"lord":"轩辕氏","call":"传说中的黄帝","birth":null,"death":null,"burial":null,"status":"legendary_or_disputed","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":24,"note":"传说时代人物，不填传说纪年"}],
  "yandi-ling": [{"lord":"神农氏","call":"传说中的炎帝","birth":null,"death":null,"burial":null,"status":"legendary_or_disputed","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":25,"note":"传说时代人物"}],
  "zhou-ling": [{"lord":"姬昌","call":"周文王","birth":null,"death":null,"burial":null,"status":"legendary_or_disputed","attribution":"presumed","src":"supplement","line":26,"ysrc":null,"yline":null,"note":"源在生卒葬三格写作「传统纪年」与 unknown_burial；名册作「旧传周文王、周武王」，故归属标 presumed"}, {"lord":"姬发","call":"周武王","birth":null,"death":null,"burial":null,"status":"legendary_or_disputed","attribution":"presumed","src":"supplement","line":26,"ysrc":null,"yline":null,"note":"源在生卒葬三格写作「传统纪年」与 unknown_burial；名册作「旧传周文王、周武王」，故归属标 presumed"}],
  "wanan-ling": [{"lord":"陈霸先","call":"陈武帝","birth":503,"death":559,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":68,"note":null}],
  "wanan-ling2": [{"lord":"齐宣帝萧承之","call":null,"birth":null,"death":447,"burial":null,"status":"legendary_or_disputed","attribution":"confirmed","src":"supplement","line":23,"ysrc":"supplement","yline":23,"note":"陵号与陵址存争议；与「南齐泰安陵」是否同一对象仍未定论"}],
  "gaoping-ling": [{"lord":"曹叡","call":"魏明帝","birth":205,"death":240,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":29,"note":null}],
  "longyao-tang-zuling": [{"lord":"李熙","call":"建初陵","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"supplement","line":27,"ysrc":null,"yline":null,"note":"河北省文物局定为二陵同茔，生卒均不可靠确定"}, {"lord":"李天赐","call":"启运陵","birth":null,"death":null,"burial":null,"status":"unknown_years","attribution":"confirmed","src":"supplement","line":27,"ysrc":null,"yline":null,"note":"河北省文物局定为二陵同茔，生卒均不可靠确定"}],
  "zhongshan-ling": [{"lord":"孙中山","call":null,"birth":1866,"death":1925,"burial":1929,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"supplement","yline":22,"note":"1929-06-01 奉安迁葬南京"}],
  "doc-1": [{"lord":"秦二世胡亥","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-2": [{"lord":"秦三世子婴","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-15": [{"lord":"孺子婴刘婴（王莽摄政，6－9年皇太子）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-17": [{"lord":"汉明帝刘庄","call":null,"birth":29,"death":76,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-30": [{"lord":"魏齐王曹芳","call":null,"birth":231,"death":274,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":30,"note":null}],
  "doc-31": [{"lord":"魏高贵乡公曹髦","call":null,"birth":241,"death":260,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":31,"note":null}],
  "doc-32": [{"lord":"魏元帝曹奂","call":null,"birth":245,"death":302,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":32,"note":null}],
  "doc-34": [{"lord":"后主刘禅","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-36": [{"lord":"会稽王孙亮","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-37": [{"lord":"景帝孙休","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-38": [{"lord":"乌程侯孙皓","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-39": [{"lord":"宣帝司马懿（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-40": [{"lord":"景帝司马师（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-41": [{"lord":"文帝司马昭（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-42": [{"lord":"武帝司马炎","call":null,"birth":236,"death":290,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-43": [{"lord":"惠帝司马衷","call":null,"birth":259,"death":306,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":40,"note":null}],
  "doc-44": [{"lord":"怀帝司马炽","call":null,"birth":283,"death":313,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":41,"note":null}],
  "doc-45": [{"lord":"愍帝司马邺","call":null,"birth":270,"death":317,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":42,"note":null}],
  "doc-46": [{"lord":"元帝司马睿","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-47": [{"lord":"明帝司马绍","call":null,"birth":299,"death":325,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":44,"note":null}],
  "doc-48": [{"lord":"成帝司马衍","call":null,"birth":320,"death":342,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":45,"note":null}],
  "doc-49": [{"lord":"康帝司马岳","call":null,"birth":322,"death":344,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":46,"note":null}],
  "doc-50": [{"lord":"穆帝司马聃","call":null,"birth":342,"death":361,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":47,"note":null}],
  "doc-51": [{"lord":"哀帝司马丕","call":null,"birth":340,"death":365,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":48,"note":null}],
  "doc-52": [{"lord":"海西公（废帝）司马奕","call":null,"birth":342,"death":386,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":49,"note":null}],
  "doc-53": [{"lord":"简文帝司马昱","call":null,"birth":320,"death":372,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":50,"note":null}],
  "doc-54": [{"lord":"孝武帝司马曜","call":null,"birth":362,"death":396,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":51,"note":null}],
  "doc-55": [{"lord":"安帝司马德宗","call":null,"birth":382,"death":418,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":52,"note":null}],
  "doc-56": [{"lord":"恭帝司马德文","call":null,"birth":385,"death":421,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":53,"note":null}],
  "doc-57": [{"lord":"武帝刘裕","call":null,"birth":363,"death":422,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-58": [{"lord":"少帝刘义符","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-59": [{"lord":"文帝刘义隆","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-60": [{"lord":"孝武帝刘骏","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-61": [{"lord":"前废帝刘子业","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-62": [{"lord":"明帝刘彧","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-63": [{"lord":"后废帝刘昱","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-64": [{"lord":"顺帝刘准","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-65": [{"lord":"宣帝萧承之（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-66": [{"lord":"高帝萧道成","call":null,"birth":427,"death":482,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":59,"note":null}],
  "doc-67": [{"lord":"武帝萧赜","call":null,"birth":440,"death":493,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":60,"note":null}],
  "doc-68": [{"lord":"东昏侯萧宝卷","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-69": [{"lord":"和帝萧宝融","call":null,"birth":485,"death":502,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":62,"note":null}],
  "doc-70": [{"lord":"文帝萧顺之（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-71": [{"lord":"武帝萧衍","call":null,"birth":null,"death":549,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-72": [{"lord":"简文帝萧纲","call":null,"birth":503,"death":551,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":64,"note":null}],
  "doc-73": [{"lord":"元帝萧绎","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-74": [{"lord":"敬帝萧方智","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-76": [{"lord":"文帝陈蒨","call":null,"birth":522,"death":566,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":69,"note":null}],
  "doc-77": [{"lord":"废帝陈伯宗","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-78": [{"lord":"宣帝陈顼","call":null,"birth":531,"death":582,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":71,"note":null}],
  "doc-79": [{"lord":"后主陈叔宝","call":null,"birth":553,"death":604,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":72,"note":null}],
  "doc-80": [{"lord":"道武帝拓跋珪","call":null,"birth":371,"death":409,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-81": [{"lord":"明元帝拓跋嗣","call":null,"birth":392,"death":424,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":74,"note":null}],
  "doc-82": [{"lord":"太武帝拓跋焘","call":null,"birth":null,"death":452,"burial":null,"status":"unknown_birth","attribution":"confirmed","src":"roster","line":null,"ysrc":"cbdb","yline":null,"note":null}],
  "doc-83": [{"lord":"南安王拓跋余（未逾年改元，旋被废）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-84": [{"lord":"文成帝拓跋濬","call":null,"birth":440,"death":466,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":76,"note":null}],
  "doc-85": [{"lord":"献文帝拓跋弘","call":null,"birth":455,"death":476,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":77,"note":null}],
  "doc-87": [{"lord":"宣武帝元恪","call":null,"birth":483,"death":515,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":79,"note":null}],
  "doc-89": [{"lord":"幼主元钊","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-90": [{"lord":"孝庄帝元子攸","call":null,"birth":509,"death":530,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":81,"note":null}],
  "doc-91": [{"lord":"长广王元晔","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-92": [{"lord":"节闵帝元恭","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-93": [{"lord":"安定王元朗","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-94": [{"lord":"孝武帝元修","call":null,"birth":510,"death":534,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":82,"note":null}],
  "doc-95": [{"lord":"东魏孝静帝元善见","call":null,"birth":524,"death":551,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":83,"note":null}],
  "doc-96": [{"lord":"西魏文帝元宝炬","call":null,"birth":507,"death":551,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":84,"note":null}],
  "doc-97": [{"lord":"西魏废帝元钦","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-98": [{"lord":"西魏恭帝拓跋廓（元廓）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-99": [{"lord":"神武帝高欢（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-100": [{"lord":"文襄帝高澄（追尊）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-101": [{"lord":"文宣帝高洋","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-102": [{"lord":"废帝高殷","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-103": [{"lord":"孝昭帝高演","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-104": [{"lord":"武成帝高湛","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-105": [{"lord":"后主高纬","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-106": [{"lord":"安德王高延宗（称制两日，降王礼）","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-107": [{"lord":"幼主高恒","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-108": [{"lord":"范阳王高绍义","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-110": [{"lord":"孝闵帝宇文觉","call":null,"birth":542,"death":557,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":93,"note":null}],
  "doc-111": [{"lord":"明帝宇文毓","call":null,"birth":534,"death":560,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":94,"note":null}],
  "doc-113": [{"lord":"宣帝宇文赟","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-114": [{"lord":"静帝宇文阐","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-117": [{"lord":"隋恭帝杨侑","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}],
  "doc-137": [{"lord":"唐哀帝李柷","call":null,"birth":892,"death":908,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":120,"note":null}],
  "doc-167": [{"lord":"惠帝朱允炆","call":null,"birth":1377,"death":1402,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":195,"note":null}],
  "doc-172": [{"lord":"代宗朱祁钰","call":null,"birth":1428,"death":1457,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":200,"note":null}],
  "doc-180": [{"lord":"熹宗朱由校","call":null,"birth":1605,"death":1627,"burial":null,"status":"ok","attribution":"confirmed","src":"roster","line":null,"ysrc":"emperors","yline":208,"note":null}],
  "doc-193": [{"lord":"宣统帝溥仪","call":null,"birth":null,"death":null,"burial":null,"status":null,"attribution":"confirmed","src":"roster","line":null,"ysrc":null,"yline":null,"note":null}]
 }}));
